# -*- coding: utf-8 -*-
"""gender-speech-duration-calculator.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nQcQVYyrcPsd6q_qW3WUAkpv618oIuc4

##**Gender-speech-duration-calculator**
Here you will find a tool to calculate the percentage of time of female voice speech and male voice speech in a video/movie. You can either choose to paste a youtube link or you can upload your video. Install the program, choose one option and calculate the percentage of female and male speech.

##**Step 1: installation**
"""

#@title Install gender-speech-duration-calculator 
!apt-get install ffmpeg
!pip install inaSpeechSegmenter
!pip install youtube_dl
!pip install -qU ddsp
from google.colab import output
output.clear()

"""##**Step 2: upload/paste video**"""

#@title Option 1: paste your youtube link here
import youtube_dl
youtube_link= 'https://www.youtube.com/watch?v=UG_X_7g63rY&t=23s' #@param {type:"string"}
ydl_opts = {
    'format': 'bestaudio/best',
    'postprocessors': [{
        'key': 'FFmpegExtractAudio',
        'preferredcodec': 'mp3',
        'preferredquality': '192',
    }],
    'outtmpl': 'audio.%(etx)s',
    'quiet': False
}

with youtube_dl.YoutubeDL(ydl_opts) as ydl:
    ydl.download([youtube_link])  
output.clear()

#@title Option 2: click here to upload your video (it has to be mp4 format).
import moviepy.editor as mp
from ddsp.colab.colab_utils import upload

filenames, audios = upload()
tuple_file=filenames, audios[0][0]
video=tuple_file[0][0]
clip = mp.VideoFileClip("/content/"+video).subclip(0,20)
clip.audio.write_audiofile("audio.mp3")

"""##**Step 3: compute percentage**"""

#@title Click here to calculate the percentage of female/male voice speech (this may take a while).

from inaSpeechSegmenter import Segmenter, seg2csv
media = 'audio.mp3'
seg = Segmenter()
segmentation = seg(media)

female=0
male=0

for i in segmentation:
  duration = i[2] - i[1]
  if i[0] == "female":
    female=female + duration
  elif i[0] == "male":
    male=male + duration
total_speech= female + male

def percentage(part, whole):
  return 100 * float(part)/float(whole)

percentage_female=round(percentage(female, total_speech), 2)
percentage_male=round(percentage(male, total_speech), 2)
output.clear()
print("RESULTS:")
print("Female voice speech: "+str(percentage_female)+ "%.")
print("Male voice speech: "+str(percentage_male)+"%.")

"""##Important note: 
Although we acknowledge there are many more genders than male/female, and that there is no such thing as a "woman's voice" or a "man's voice",  this tool tries its best to make a contribution to make gender inequality more visible. Hopefully in the future there will be more developed tools that fight gender inequality for all genders.
"""